---
title: Payrolls of the Cleveland Baseball Team
author: Derek Sollberger
date: '2021-01-07'
slug: payrolls-of-the-cleveland-baseball-team
categories:
  - sports analytics
tags:
  - ggplot
header:
  caption: ''
  image: ''
  preview: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
```

Today I made a quick graph of the player payrolls for the Cleveland baseball team to compare their projected payroll after today's trade with the Mets (Lindor, Carrasco, etc.) to past seasons.

Sources:

* (past) http://www.stevetheump.com/Payrolls.htm
* (2021 projection) https://twitter.com/ZackMeisel/status/1347246681520295936
* https://teamcolorcodes.com/cleveland-indians-color-codes/

```{r}
years <- 2014:2021
payrolls <- c(82.5, 86.1, 86.3, 124.3, 134.4, 88.7, 37.6, 35)
df <- data.frame(years, payrolls)
```

```{r}
df %>%
  ggplot(aes(x = years, y = payrolls, label = payrolls)) +
  geom_bar(stat = "identity", fill = "#E31937", color = "#0C2340") +
  geom_label() +
  labs(title = "Opening Day Payrolls of the Cleveland Baseball Team",
       subtitle = "2016: World Series appearance\n2020: pandemic-shortened season\n2021: projected",
       caption = "Sources:  http://www.stevetheump.com/Payrolls.htm \n https://twitter.com/ZackMeisel/status/1347246681520295936",
       x = "season", y = "payroll (in millions of dollars)") +
  scale_x_continuous(breaks = 2014:2021, 
                     labels = c("2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021")) +
  theme_minimal()
```