---
title: Harriet Tubman's Lifespan
author: Derek Sollberger
date: '2022-02-26'
slug: []

header:
  caption: ''
  image: ''
  preview: yes
---

On Twitter, @Cmastication said that "Just read this and it made my head hurt. Fact checked it an it’s correct: “when Harriet Tubman was born, Thomas Jefferson was alive, and when Harriet Tubman died, Ronald Reagan was alive.”", so I felt like making a quick visualization.  We will line up some implied rectangles using `geom_jitter`.

```{r setup, message = FALSE, warning = FALSE}
library("tidyverse")
N <- 1000

df <- data.frame(
  year = c(runif(N, 1743, 1826),
              runif(N, 1822, 1913),
              runif(N, 1911, 2004)),
  person = c(rep("Jefferson", N), rep("Tubman", N), rep("Reagan", N)))

df$person <- factor(df$person,
                    levels = c("Reagan", "Tubman", "Jefferson"))
```

```{r viz}
df |>
  ggplot() +
  geom_jitter(aes(x = year, y = person, color = person)) +
  labs(title = "Harriet Tubman's Life",
       subtitle = "among other historical figures",
       x = "Year",
       y = "") +
  theme(legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_line(color = "gray50"),
        panel.grid.major.x = element_blank(),
        plot.subtitle = element_text(color = "black", 
                                     hjust = 0.5, size = 15),
        plot.title = element_text(color = "black", 
                                  hjust = 0.5, size = 20))
```